
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8">
            
                    <h1 class="page-header">
                        Page Heading
                        <small>Secondary Text</small>
                        <?php
                        if(SessionUserIsAdmin())
                        {
                            ?>
                            <div class="pull-right">
                                <small class="text-right" ><a href="admin/posts.php?source=edit_post&pid=<?php echo $this->post->post_id ?>">Edit this post</a></small>
                            </div>
                            <?php

                        }
                        ?>
                    </h1>

                    <!-- Blog Post -->
                    <h2>
                        <a href="post.php?pid=<?php echo $this->post->post_id ?>"><?php echo $this->post->post_title ?></a>
                    </h2>
                    <p class="lead">
                        by <a href="user_posts.php?id=<?php echo $this->post->post_author ?>"><?php echo $this->post->post_author_name ?></a>
                    </p>
                    <p><span class="glyphicon glyphicon-time"></span> Posted on <?php echo $this->post->post_date ?></p>
                    <hr>
                    <img class="img-responsive" src="images/<?php echo $this->post->post_image ?>" alt="">
                    <hr>
                    <p><?php echo $this->post->post_content ?></p>

                    <hr>
                <!-- Blog Comments -->
                <!-- Post form -->
                <div class="well">
                    <h4>Leave a Comment:</h4>
                    <form role="form" action="" method="post">
                        <div class="form-group">
                            <label for="comment_author">Name</label>
                            <input type="text" name="comment_author" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="comment_author">Email</label>
                            <input type="email" name="comment_email" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="comment_content">Message</label>
                            <textarea class="form-control" rows="3" name="comment_content"></textarea>
                        </div>
                        <button type="submit" name="create_comment" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            <?php foreach($this->post->comments as $comment) {
            ?>
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading"><?php echo $comment->comment_author ?>
                            <small><?php echo $comment->comment_date ?></small>
                        </h4>
                        <?php echo $comment->comment_content ?>
                    </div>
                </div>

                <?php
            }
            ?>

            <hr>
        </div>
    </div>
    <!-- /.row -->

    <hr>