<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?php echo $this->pageName; ?></title>
    <!-- Load any controller defined css -->
    <!--    --><?php //if($this->methodExists('getUserCss'))
    //    {
    //        $this->getUserCss();
    //    } ?>
    <?php $this->renderStyles(); ?>
    <!-- Bootstrap Core CSS -->
    <!--    <link href="/css/bootstrap.min.css" rel="stylesheet">-->
    <!---->
    <!--    <!-- Custom CSS -->
    <!--    <link href="/css/blog-home.css" rel="stylesheet">-->
    <!---->
    <!--    <!-- jQuery -->
    <!--    <script src="/scripts/jquery.js"></script>-->
    <!--    --><?php //if($this->methodExists('getUserScripts'))
    //	{
    //	    $this->getUserScripts();
    //	} ?>
    <?php $this->renderScripts(); ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
<!-- Page Content -->
<div class="container">

    <?php
    // body goes in here
    $this->render($this->bodyView);
    ?>
    <!-- Footer -->
    <footer>
        <?php
        if(!$this->hideCopyright)
        { ?>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Simon Preston <?php echo date('Y') ?></p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <?php
        }
        ?>
    </footer>

</div>
<!-- /.container -->

<!-- Bootstrap Core JavaScript -->
<?php $this->renderScripts('AfterPageLoad'); ?>

</body>

</html>
