<?php ob_start(); ?>
<?php //require_once(SITE_INCLUDES . "/DatabaseHandler.php") ?>
<?php //require_once(SITE_INCLUDES . "/DatabaseCommands.php") ?>
<?php //require_once(SITE_INCLUDES . "/Functions.php") ?>

<?php include_once("C:\\Repo\\Devpond.php.mvc\\Devpond.php.mvc\\libs\\DatabaseHandler.php") ?>
<?php include_once("C:\\Repo\\Devpond.php.mvc\\Devpond.php.mvc\\libs\\DatabaseCommands.php") ?>
<?php include_once("C:\\Repo\\Devpond.php.mvc\\Devpond.php.mvc\\libs\\Functions.php") ?>

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?php echo $this->pageName ?></title>

    <!-- Bootstrap Core CSS -->
    <link href="/css/admin/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/css/admin/sb-admin.css" rel="stylesheet">
    <link href="/css/admin/loader.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/css/admin/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery -->
    <script src="/scripts/jquery.js"></script>
    <script src="/scripts/scripts.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>

<body>
<div id="wrapper">
    <!-- Navigation -->
    <?php //require_once(VIEW_PARTIALS . "../../views/partials/navigation.phtml") ?>
    <?php include_once("C:\\Repo\\Devpond.php.mvc\\Devpond.php.mvc\\views\\partials\\admin_navigation.phtml") ?>
    <div id="page-wrapper">
        <?php $this->renderBody($this->bodyView); ?>
    </div>

</div>
<!-- /#wrapper -->


<script src="/scripts/tinymce/tinymce.min.js"></script>


<script src="/scripts/admin.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/scripts/bootstrap.min.js"></script>
</body>

</html>