<?php
if(isset($_SESSION['firstname']))
{
    $firstname = $_SESSION['firstname'];
}
if(isset($_SESSION['lastname']))
{
    $lastname = $_SESSION['lastname'];
}
?>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/Admin">CMS Admin</a>
    </div>
    <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">
        <!-- <li><a href="#">Users Online: <?php echo UsersOnlineCount(); ?></a><li> -->
        <li><a href="#">Users Online: <span id="users_online" class="users_online"></span></a></li>
        <li><a href="/Index">Home</a></li>

        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <?php echo $firstname . " " . $lastname ?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="/User/Logout"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                </li>
            </ul>
        </li>
    </ul>
    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">

            <li<?php if($this->pageName == "AdminHome") {echo " class='active'";} ?>>
                <a href="/Admin"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
            </li>

            <li<?php if($this->pageName == "AdminPosts") {echo " class='active'";} ?>>
                <a href="javascript:;" data-toggle="collapse" data-target="#posts_dropdown"><i class="fa fa-fw fa-arrows-v"></i> Posts <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="posts_dropdown" class="collapse">
                    <li>
                        <a href="/Admin/ViewPosts">View All Posts</a>
                    </li>
                    <li>
                        <a href="/Admin/AddPosts">Add Posts</a>
                    </li>
                </ul>
            </li>

            <li<?php if($this->pageName == "AdminCategories") {echo " class='active'";} ?>>
                <a href="/Admin/Categories"><i class="fa fa-fw fa-wrench"></i> Categories</a>
            </li>

            <li<?php if($this->pageName == "AdminComments") {echo " class='active'";} ?>>
                <a href="comments.php"><i class="fa fa-fw fa-file"></i> Comments</a>
            </li>

            <li<?php if($this->pageName == "AdminUsers") {echo " class='active'";} ?>>
                <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Users <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="demo" class="collapse">
                    <li>
                        <a href="Admin/ViewUsers">View All Users</a>
                    </li>
                    <li>
                        <a href="Admin/AddUsers">Add User</a>
                    </li>
                </ul>
            </li>
            <li<?php if($this->pageName == "AdminProfile") {echo " class='active'";} ?>>
                <a href="/Admin/Profile"><i class="fa fa-fw fa-wrench"></i> Profile</a>
            </li>
            <li<?php if($this->pageName == "AdminInfo") {echo " class='active'";} ?>>
                <a href="/Admin/Info"><i class="fa fa-fw fa-wrench"></i> Info</a>
            </li>
        </ul>
    </div>
    <!-- /.navbar-collapse -->
</nav>