<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/Index">HOME</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <?php
                    foreach($this->menuLinks as $menuLink)
                    {
                        echo "<li  class='{$menuLink['cat_class']}'><a href='/Category?id={$menuLink['cat_id']}'>{$menuLink['cat_title']}</a></li>";
                    }
                ?>
                <li<?php if($this->pageName == "Contact") {echo " class='active'";} ?>>
                    <a href="/Contact">Contact</a>
                </li>
                <?php
                if($this->isLoggedIn)
                {
                    if($this->isAdmin)
                    {
                        ?>
                        <li>
                            <a href="/Admin">Admin</a>
                        </li>
                        <?php
                    } ?>
                    <li>
                        <a href="/User/Logout">Logout</a>
                    </li>
                    <?php
                }
                else { ?>
                    <li<?php if($this->pageName == "Register") {echo " class='active'";} ?>>
                        <a href="/Register">Register</a>
                    </li> <?php } ?>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>