
    <section id="login">
            <div class="row">
                <div class="col-xs-6 col-xs-offset-3">
                    <div class="form-wrap">
                        <h1>Contact</h1>
                        <form role="form" action="Contact/contact" method="post" id="contact_form">
                            <div class="form-group">
                                <label for="subject" class="sr-only">Subject</label>
                                <input type="text" required name="subject" id="subject" class="form-control" placeholder="What is the topic...">
                            </div>

                            <div class="form-group">
                                <label for="name" class="sr-only">Name</label>
                                <input type="text" required name="name" id="name" class="form-control" placeholder="Your name here...">
                            </div>
                            <div class="form-group">
                                <label for="email" class="sr-only">Email</label>
                                <input type="email" required name="email" id="email" class="form-control" placeholder="And your email address...">
                            </div>
                            <div class="form-group">
                                <label for="message" class="sr-only">Your message</label>
                                <textarea rows="3" required name="message" id="message" class="form-control" placeholder="What do you need to tell me?"></textarea>
                            </div>

                            <input type="submit" name="submit" id="btn-login" class="btn btn-custom btn-lg btn-block" value="Submit">
                        </form>
                    </div>
                </div> <!-- /.col-xs-12 -->
            </div> <!-- /.row -->
    </section>
    <hr>